### Health Check
GET http://localhost:8000/api/v1/health

### AUTH Operations ###
### signup User
POST http://localhost:8000/api/v1/auth/local/signup
Content-Type: application/json

{
  "fullName": "Freshiadoe",
  "email": "Freshia@example.com",
  "password": "secretpass123",
  "role": "ADMIN",
  "username": "freshiadoe"
}

### signin User
POST http://localhost:8000/api/v1/auth/local/signin
Content-Type: application/json

{
  "email": "Freshia@example.com",
  "password": "secretpass123"
}


### Users CRUD Operations ###


### Get All Users
GET http://localhost:8000/api/v1/users

### Get User by ID
GET http://localhost:8000/api/v1/users/1

### Update User
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "username": "johnupdated",
  "email": "john.updated@example.com"
}

### Delete User
DELETE http://localhost:8000/api/v1/users/1

### Company CRUD Operations ###

### Get Company details
GET http://localhost:8000/api/v1/company

### Create Company
POST http://localhost:8000/api/v1/company
Content-Type: application/json

{
  "companyName": "FreshiaTech",
  "address": "123, Freshia Street, Freshia City", 
  "phone": "1234567890",
  "email": "freshia@gmail.com",
  "taxId": "1234567890"
}

### GET Companies via ID
GET http://localhost:8000/api/v1/company/87f34491-b0f7-437c-acf8-f5e4899d85fa

### Update Company
PATCH http://localhost:8000/api/v1/company/87f34491-b0f7-437c-acf8-f5e4899d85fa
Content-Type: application/json

{
  "email": "freshiatech@gmail.com"
}

### Delete Company
DELETE http://localhost:8000/api/v1/company/87f34491-b0f7-437c-acf8-f5e4899d85fa

### categories CRUD Operations ###
### Create Category
POST http://localhost:8000/api/v1/categories
Content-Type: application/json

{
  "categoryName": "Electronics",
  "description": "All electronics items"
}

### Get All Categories
GET http://localhost:8000/api/v1/categories

### Get Category by ID
GET http://localhost:8000/api/v1/categories/1

### Update Category
PATCH http://localhost:8000/api/v1/categories/1
Content-Type: application/json

{
  "categoryName": "Electronics",
  "description": "All electronics items"
}

### Delete Category
DELETE http://localhost:8000/api/v1/categories/1

### Customers CRUD Operations ###
### Create Customers
POST http://localhost:8000/api/v1/customers
Content-Type: application/json

{
  "firstName": "Freshia",
  "lastName": "Doe",
  "email": "freshia@gmail.com",
  "phone": "1234567890",
  "address": "123, Freshia Street, Freshia City"
}

### Get All Customers
GET http://localhost:8000/api/v1/customers

### Get Customer by ID
GET http://localhost:8000/api/v1/customers/1

### Update Customer
PATCH http://localhost:8000/api/v1/customers/1
Content-Type: application/json

{
  "lastName": "Njoki",
  "email": "freshia@outlook.com"
}

### Delete Customer
DELETE http://localhost:8000/api/v1/customers/1

### Inventory CRUD Operations ###
### Create Inventory
POST http://localhost:8000/api/v1/inventory
Content-Type: application/json

{
  "productId": 1,
  "quantity": 3,
  "reorderLevel": 1
}

### Get All Inventory
GET http://localhost:8000/api/v1/inventory

### Get Inventory by ID
GET http://localhost:8000/api/v1/inventory/1

### Update Inventory
PATCH http://localhost:8000/api/v1/inventory/1
Content-Type: application/json

{
  "quantity": 1,
}

### Delete Inventory
DELETE http://localhost:8000/api/v1/inventory/1

### Product  Operations ###
### Create Product
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
  "categoryId": 1,
  "supplierId": 1,
  "productName": "Laptop",
  "description": "Dell Laptop",
  "sku": "123456",
  "unitPrice": 1000.00,
  "taxRate": 0.00
}

### Get All Products
GET http://localhost:8000/api/v1/products

### Get Product by ID
GET http://localhost:8000/api/v1/products/1

### Update Product
PATCH http://localhost:8000/api/v1/products/1
Content-Type: application/json

{
  "unitPrice": 1200.00
}

### Delete Product
DELETE http://localhost:8000/api/v1/products/1

### Stock Operations ###
### Create Stock transaction
POST http://localhost:8000/api/v1/stock-management/with-inventory-update
Content-Type: application/json

{
  "inventoryId": 1,
  "stockManagementType": ADDITION,
  "quantityChange": 10,
  "reference": "Stock Addition"
}

### Purchase Order Operations ###
### patch Purchase Order transaction
PATCH http://localhost:8000/api/v1/purchase-orders/1/receive-purchase-order
