### Health Check
GET http://localhost:8000/api/v1/health

### Users CRUD Operations ###

### Create User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "username": "Freshiadoe",
  "email": "Freshia@example.com",
  "password_hash": "secretpass123",
  "role": "ADMIN"
}

### Get All Users
GET http://localhost:8000/api/v1/users

### Get User by ID
GET http://localhost:8000/api/v1/users/1

### Update User
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "username": "johnupdated",
  "email": "john.updated@example.com"
}

### Delete User
DELETE http://localhost:8000/api/v1/users/1

### Company CRUD Operations ###

### Get Company details
GET http://localhost:8000/api/v1/company