### Health Check
GET http://localhost:8000/api/v1/health

### AUTH Operations ###
### signup User
POST http://localhost:8000/api/v1/auth/local/signup
Content-Type: application/json

{
  "fullName": "Freshiadoe",
  "email": "Freshia@example.com",
  "password": "secretpass123",
  "role": "ADMIN",
  "username": "freshiadoe"
}

### signin User
POST http://localhost:8000/api/v1/auth/local/signin
Content-Type: application/json

{
  "email": "Freshia@example.com",
  "password": "secretpass123"
}


### Users CRUD Operations ###


### Get All Users
GET http://localhost:8000/api/v1/users

### Get User by ID
GET http://localhost:8000/api/v1/users/1

### Update User
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "username": "johnupdated",
  "email": "john.updated@example.com"
}

### Delete User
DELETE http://localhost:8000/api/v1/users/1

### Company CRUD Operations ###

### Get Company details
GET http://localhost:8000/api/v1/company

### Create Company
POST http://localhost:8000/api/v1/company
Content-Type: application/json

{
  "companyName": "FreshiaTech",
  "address": "123, Freshia Street, Freshia City", 
  "phone": "1234567890",
  "email": "freshia@gmail.com",
  "taxId": "1234567890"
}

### GET Companies via ID
GET http://localhost:8000/api/v1/company/87f34491-b0f7-437c-acf8-f5e4899d85fa

### Update Company
PATCH http://localhost:8000/api/v1/company/87f34491-b0f7-437c-acf8-f5e4899d85fa
Content-Type: application/json

{
  "email": "freshiatech@gmail.com"
}

### Delete Company
DELETE http://localhost:8000/api/v1/company/87f34491-b0f7-437c-acf8-f5e4899d85fa

### categories CRUD Operations ###
### Create Category
POST http://localhost:8000/api/v1/categories
Content-Type: application/json

{
  "categoryName": "Electronics",
  "description": "All electronics items"
}

### Get All Categories
GET http://localhost:8000/api/v1/categories

### Get Category by ID
GET http://localhost:8000/api/v1/categories/1

### Update Category
PATCH http://localhost:8000/api/v1/categories/1
Content-Type: application/json

{
  "categoryName": "Electronics",
  "description": "All electronics items"
}

### Delete Category
DELETE http://localhost:8000/api/v1/categories/1

### Product CRUD Operations ###
### Create Product
POST http://localhost:8000/api/v1/product
Content-Type: application/json

{
  "productName": "Laptop",
  "description": "Dell Inspiron 15 3000",
  "price": 50000,
  "quantity": 10,
  "categoryId": 1
}
