services:
  # Development service
  # Database service (PostgreSQL)
  pos-db-dev-service:
    image: postgres:17-alpine
    container_name: pos-db-dev-container
    ports:
      - '5433:5432'
    env_file:
      - .env.development
    volumes:
      - postgres-data-dev-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pos-dev-network
    profiles:
      - development
  # API service (NESTJS)
  pos-api-dev-service:
    container_name: pos-api-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "./scripts/wait-for-it.sh pos-db-dev-service 5432 && pnpm prisma:migrate && pnpm run start:dev"
    depends_on:
      pos-db-dev-service:
        condition: service_healthy
      pos-redis-dev-service:
        condition: service_started
    networks:
      - pos-dev-network
    profiles:
      - development
  # REdis service
  pos-redis-dev-service:
    image: redis:alpine
    container_name: pos-redis-dev-container
    # command: ['redis-server', '--requirepass', '123']
    ports:
      - '6379:6379'
    volumes:
      - pos-cache-volume:/data
    networks:
      - pos-dev-network
    profiles:
      - development

  # Production service
  # Database service (PostgreSQL)
  pos-db-prod-service:
    image: postgres:17-alpine
    container_name: pos-db-prod-container
    ports:
      - '5432:5432'
    env_file:
      - .env.production
    volumes:
      - postgres-data-prod-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pos-prod-network
    profiles:
      - production
  # API service (NESTJS)
  pos-api-prod-service:
    container_name: pos-api-prod-container
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner
    env_file:
      - .env.production
    ports:
      - '8080:8080'
    command: sh -c "./scripts/wait-for-it.sh pos-db-prod-service 5432 && pnpm prisma:migrate && pnpm run start:prod"
    depends_on:
      pos-db-prod-service:
        condition: service_healthy
      pos-redis-prod-service:
        condition: service_started
    networks:
      - pos-prod-network
    profiles:
      - production
# REdis service
  pos-redis-prod-service:
    image: redis:alpine
    container_name: pos-redis-prod-container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env.production
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - pos-cache-volume:/data
    networks:
      - pos-prod-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - production
volumes:
  postgres-data-dev-volume:
  postgres-data-prod-volume:
  pos-cache-volume:
    driver: local

networks:
  pos-dev-network:
    driver: bridge
  pos-prod-network:
    driver: bridge
